#\u751F\u4EA7\u73AF\u5883\u914D\u7F6E
server:
  #\u670D\u52A1\u5668\u7AEF\u53E3
  port: 8081
  #\u751F\u4EA7\u73AF\u5883\u6570\u636E\u5E93\u8FDE\u63A5\u914D\u7F6E
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: abc1994429
    driver-class-name: com.mysql.cj.jdbc.Driver
