#\u5F00\u53D1\u73AF\u5883\u914D\u7F6E

server:
  #\u670D\u52A1\u5668\u7AEF\u53E3
  port: 8082
  #\u5F00\u53D1\u73AF\u5883\u6570\u636E\u5E93\u8FDE\u63A5\u914D\u7F6E
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: abc1994429
    driver-class-name: com.mysql.cj.jdbc.Driver

#\u5F00\u53D1\u73AF\u5883\u4E0B\uFF0C\u5F00\u542Fmybatis\u7684\u65E5\u5FD7\u5B9E\u73B0\uFF0C\u6253\u5370mysql\u6267\u884C\u8BED\u53E5
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl